version: "3.1"

networks:
  internal-only-network:
    driver: bridge

services:
  #######################################
  backend:
    build: ./backend
    container_name: nodejs
    # Data
    env_file:
      - backend/.env
    # working_dir: /app
    volumes:
      - ./backend/src:/app/src
    # Run
    command: npm run dev
    # Connectivity
    # networks:
    #   - internal-only-network
    ports:
      - 127.0.0.1:4000:4000
    # Misc
    # depends_on:
    #   - database